name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: List of Fruits Test
      id: list-of-fruits-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: List of Fruits Test
        setup-command: ''
        command: python3 favorite_fruits/main.py
        input: ''
        expected-output: "^.+\\n.+\\n.+\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LIST-OF-FRUITS-TEST_RESULTS: "${{steps.list-of-fruits-test.outputs.result}}"
      with:
        runners: list-of-fruits-test
